<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CRISP.Domain\CRISP.Domain.csproj" />
    <ProjectReference Include="..\CRISP.Application\CRISP.Application.csproj" />
    <ProjectReference Include="..\..\Libraries\RulesEngine\RulesEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
  </ItemGroup>
</Project>
